[scripts]
test = "yarn ts-mocha -t 30000"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "QMMD16kjauP5knBwxNUJRZ1Z5o3deBuFrqVjBVmmqto"
program = "./target/deploy/quarry_merge_mine.so"

[[test.genesis]]
address = "QMNeHCGYnLVDn1icRAfQZpjPLBNkfGbSKRB83G5d8KB"
program = "./target/deploy/quarry_mine.so"

[[test.genesis]]
address = "QMWoBmAyJLAsA1Lh9ugMTw2gciTihncciphzdNzdZYV"
program = "./target/deploy/quarry_mint_wrapper.so"

[[test.genesis]]
address = "QoP6NfrQbaGnccXQrMLUkog2tQZ4C1RFgJcwDnT8Kmz"
program = "./target/deploy/quarry_operator.so"

[[test.genesis]]
address = "QRDxhMw1P2NEfiw5mYXG79bwfgHTdasY2xNP76XSea9"
program = "./target/deploy/quarry_redeemer.so"

[[test.genesis]]
address = "QREGBnEj9Sa5uR91AV8u3FxThgP5ZCvdZUW2bHAkfNc"
program = "./target/deploy/quarry_registry.so"
