[package]
name = "quarry-registry"
version = "1.0.0"
description = "Registry of all quarries associated with a rewarder."
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "quarry_registry"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.13.2"
quarry-mine = { version = "1.0.0", path = "../quarry-mine", features = ["cpi"] }
vipers = "0.1.1"
