[package]
name = "quarry-mine"
version = "1.10.0"
description = "Distributes liquidity mining rewards to token stakers"
edition = "2018"
homepage = "https://quarry.so"
repository = "https://github.com/QuarryProtocol/quarry"
authors = ["Quarry Protocol <team@quarry.so>"]
license = "AGPL-3.0"
keywords = ["solana", "quarry"]

[lib]
crate-type = ["cdylib", "lib"]
name = "quarry_mine"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = ">=0.17.0"
anchor-spl = ">=0.17.0"
num-traits = "0.2.14"
quarry-mint-wrapper = { path = "../quarry-mint-wrapper", features = [
  "cpi"
], version = "1.10.0" }
spl-math = { version = "0.1.0", features = ["no-entrypoint"] }
vipers = "1.5.3"

[dev-dependencies]
proptest = { version = "1.0" }
rand = { version = "0.8.4" }
