[package]
name = "quarry-mine"
version = "1.5.0"
description = "Distributes liquidity mining rewards to token stakers"
edition = "2018"
homepage = "https://quarry.so"
repository = "https://github.com/QuarryProtocol/quarry"
authors = ["Quarry Protocol <team@quarry.so>"]
license = "AGPL-3.0"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "quarry_mine"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.13.2"
anchor-spl = "0.13.2"
num-traits = "0.2.14"
quarry-mint-wrapper = { path = "../quarry-mint-wrapper", features = [
  "cpi"
], version = "1.1.0" }
solana-program = "1.7.8"
spl-associated-token-account = { version = "1.0.3", features = [
  "no-entrypoint"
] }
spl-math = { version = "0.1.0", features = ["no-entrypoint"] }
vipers = "0.1.1"

[dev-dependencies]
proptest = { version = "1.0" }
rand = { version = "0.8.4" }
